### ISSUE TITLE
macOS's objdump is llvm-objdump. You need `brew install binutils` and point the app to `/usr/local/bin/gobjdump`.

### ISSUE THREAD

**Issue by lanza** [jubal-R/ObjGui#1]
As mentioned above, this app doesn't cooperate with `llvm-objdump`.

**Comment by jubal-R** [comment]
I'll have to look into llvm-objdump. I don't have a mac to test it on, but I'm guessing the Linux version of llvm-objdump will probably work about the same.

It does work ok once you run `brew install binutils` and set it to point to `/usr/local/bin/gobjdump` under options though, correct? If so I'll add these instructions to the README for mac users.

**Comment by lanza** [comment]
`llvm-objdump` provides similar functionality but uses different flags. So your app is trying to use some invocation and `llvm-objdump`'s flags disagree and it just responds with an error.

> It does work ok once you run brew install binutils and set it to point to /usr/local/bin/gobjdump under options though, correct? If so I'll add these instructions to the README for mac users.

Correct.
